defaults:
  - benchmark: dna
  - acq_fun: ei
#   - model: default
#   - acq_opt: highdim

# general
seed: 42
debug: true
float_dtype_as_int: 64
verbose: true
wandb_entity: ""
wandb_project_name: ""
run_id: ""

# elbo/eulbo
lr: 0.01
train_bsz: 32
max_allowed_n_failures_improve_loss: 3
max_allowed_n_epochs: 30
ppgpr: false
grad_clip: 2.0
n_inducing_pts: 100
update_on_n_pts: 100

# only elbo
n_update_epochs: 5
natural_gradient: false

# only eulbo
x_next_lr: 0.001
n_warm_start_epochs: 10
alternate_eulbo_updates: true

# models (see assertions)
eulbo: false
ablation1_fix_indpts_and_hypers: false
ablation2_fix_hypers: false
moss23_baseline: false
inducing_pt_init_w_moss23: true
exact_gp_baseline: true
lastn_for_exact_gp: true

# other
normalize_ys: true
init_mol_tasks_w_guacamol_data: false

#FIXME: add something about how to choose the acquisition function for warm start only?
#FIXME: or simply add KG from botorch to warm start options?